name: build-dockerimage

on:
  workflow_call:
    inputs:
      dockerfile-path:
        required: true
        type: string
      environment:
        required: true
        type: string
env:
  PACKAGE_VERSION: $(date +'%Y.%m.%d').$(echo $GITHUB_RUN_NUMBER | cut -c1-7)

jobs:
  buildimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to gh registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerfile-path }}
          push: true
          tags: |
            ${{ github.repository }}:$PACKAGE_VERSION
            ${{ github.repository }}:${{ inputs.environment }}
