name: Build and test application

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      solution-file:
        required: true
        type: string
      build-configuration:
        required: true
        type: string
      app-name:
        required: true
        type: string
    secrets:
      PACKAGE_TOKEN_SECRET:
        required: true

env:
  GITHUB_NAMESPACE: ThijmenBrand-LifeManager
  GITHUB_USERNAME: ThijmenBrand

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Add GitHub NuGet package registry
        run: dotnet nuget add source https://nuget.pkg.github.com/$GITHUB_NAMESPACE/index.json --name github --username $GITHUB_USERNAME --password ${{ secrets.PACKAGE_TOKEN_SECRET }} --store-password-in-clear-text

      - name: Restore NuGet packages
        run: dotnet restore ${{ inputs.solution-file }}

      - name: Build the project
        run: dotnet build ${{ inputs.solution-file }} --no-restore --configuration ${{ inputs.build-configuration }}

      - name: Test the project
        run: dotnet test ${{ inputs.solution-file }} --configuration Release --no-build --no-restore --results-directory "TestResults-${{ inputs.dotnet-version }}"

      - name: Setup Snyk
        uses: snyk/actions/setup@master

      - name: Snyk test
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results-${{ inputs.dotnet-version }}
          path: TestResults-${{ inputs.dotnet-version }}
        if: ${{ always() }}

  analyse:
    uses: ./.github/workflows/sonar-qube.yml
    with:
      solution-file: ${{ inputs.solution-file }}
      app-name: ${{ inputs.app-name }}
    secrets: inherit

  dependency-check:
    uses: ./.github/workflows/dependency-check.yml
