name: build-dockerimage

on:
  workflow_call:
    inputs:
      dockerfile-path:
        description: |-
          The path to the Dockerfile to build. You can put in
          multuple dockerfile paths to build multiple images.
        required: true
        type: string
      environment:
        required: true
        type: string
env:
  PACKAGE_VERSION: $(date +'%Y.%m.%d').$(echo $GITHUB_RUN_NUMBER | cut -c1-7)

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - id: matrix
        run: |
          dockerfile_paths="${{ inputs.dockerfile-path }}"
          dockerfile_paths_array=$(echo "$dockerfile_paths" | awk 'BEGIN{ORS=""; print "["} {gsub(/"/, "\\\""); printf "\"%s\", ", $0} END{print "]"}' | sed 's/, ]/]/')
          echo "value=$dockerfile_paths_array" >> $GITHUB_OUTPUT
      - run: |
          echo "${{ steps.matrix.outputs.value }}"

  buildimage:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to gh registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerfile-path }}
          push: true
          tags: |
            ${{ github.repository }}:$PACKAGE_VERSION
            ${{ github.repository }}:${{ inputs.environment }}
