name: Test application

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      solution-file:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Test the project
        run: dotnet test ${{ inputs.solution-file }} --configuration Release --no-build --no-restore --results-directory "TestResults-${{ inputs.dotnet-version }}"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results-${{ inputs.dotnet-version }}
          path: TestResults-${{ inputs.dotnet-version }}
        if: ${{ always() }}
